### ISSUE TITLE
Upgrade v1.4 to v1.6 throws error for existing web-select params missing method

### ISSUE THREAD

**Issue by westshawn** [grundic/teamcity-web-parameters#11]
```
Unexpected web-parameters error
ru.mail.teamcity.web.parameters.manager.RequestConfigurationException: Required parameter 'method' was not given!
```
Is there a better way to handle this parameter which was previously not required?

We have hundreds of existing parameters that would need to be updated once v1.6 is deployed.

**Comment by grundic** [comment]
Hello, @westshawn.
Thank you for your ticket.

Sure, I can set `GET` method as default if it's not configured, so previous configuration would still work.
If you have any other suggestions/improvements, I would be glad to help.

Thanks.

**Comment by grundic** [comment]
@westshawn, can you please try [v1.6.1](https://github.com/grundic/teamcity-web-parameters/releases/tag/v1.6.1)?
I was able to reproduce it and fix was actually quite trivial.
Give it a try :)

**Comment by westshawn** [comment]
@grundic, spasibo!!
That was fast, and just what the doctor ordered :-)

I confirmed v1.6.1 works as expected (for existing and new params).
