### ISSUE TITLE
Artifactory compatibility

### ISSUE THREAD

**Issue by unlikelygeek** [grundic/teamcity-web-parameters#15]
Hello, I'm trying to use this to connect with the JFrog Artifactory aql. The web service call returns json formatted like this where the name values are what I need to choose from:
{
"results" : [ {
  "name" : "0.1.0"
},{
  "name" : "0.1.1"
},{
  "name" : "1.0.11"
} ]
}

The teamcity-web-parameters dialog throws the following error when I call the parameter:

Failed to parse Json format
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "results" (class ru.mail.teamcity.web.parameters.data.Options), not marked as ignorable (one known property: "options"]) at [Source: org.apache.http.conn.EofSensorInputStream@5f7609; line: 3, column: 14] (through reference chain: ru.mail.teamcity.web.parameters.data.Options["results"])

Am I missing something in the configuration that will allow this format to be parsed?

Thanks for your work on this plugin!

**Comment by grundic** [comment]
Hello, @unlikelygeek!
The problem here is with json response from Artifactory: the plugin expects it to be in specific format in order to parse it, for example in your case it could be 
```
{
	"options": [{
		"key": "0.1.0",
		"value": "0.1.0"
	}, {
		"key": "0.1.1",
		"value": "0.1.1"
	}, {
		"key": "1.0.11",
		"value": "1.0.11"
	}]
}
```

Right now there is no way to redefine it from the plugin side. The only way to do it now is run separate web service, which would translate Artifactory responses to format acceptable by plugin.

Maybe some time later I could implement this behaviour in the plugin using https://github.com/bazaarvoice/jolt.

**Comment by unlikelygeek** [comment]
That's what I thought, just wanted to make sure I was not missing anything.

Thanks for the quick response!

**Comment by grundic** [comment]
I prepared transform for you, that you can try to play with on http://jolt-demo.appspot.com:
```
[
  {
    "operation": "shift",
    "spec": {
      "results": {
        "*": {
          "name": ["options[&1].key", "options[&1].value"]
        }
      }
    }
  }]
```

It should provide correct transformation from the Artifactory to plugin's format. In a meantime I'll add support of jolt so you and anyone else could use it.
Thank you for you request!

**Comment by unlikelygeek** [comment]
sweet! Thanks!

**Comment by grundic** [comment]
@unlikelygeek, please give a try to version [1.7.0](https://github.com/grundic/teamcity-web-parameters/releases/tag/v1.7.0), which includes possibility to configure JSON transformations.

**Comment by unlikelygeek** [comment]
@grundic do you have a compiled version of 1.7.0 that I can upload to TC?

**Comment by grundic** [comment]
@unlikelygeek, sure! That what's happening when doing something in hurry :) I've added zip file, so you can download it.
If you would have any issues, please let me know.

**Comment by unlikelygeek** [comment]
It works great, thanks so much @grundic !

**Comment by grundic** [comment]
:sweat_smile:

**Comment by grundic** [comment]
If you like it -- you can add a star.
