### ISSUE TITLE
How do you make the parameter to read the directory listing?

### ISSUE THREAD

**Issue by alwaysharsha** [grundic/teamcity-web-parameters#17]
Can you please let me know how do you make the parameter to read the directory listing.

Also, put the configuration of the process parameter demo.

**Comment by grundic** [comment]
Hi @alwaysharsha,
For the process demo, please have a look at the script [webserver/processes_web_server.py](https://github.com/grundic/teamcity-web-parameters/blob/master/webserver/processes_web_server.py).

To read the directory listing you can modify that script, but instead `_list_processes` method add new one named something like `_list_folder`, which could look something like:

```python
    def _list_folder(self):
        self.send_response(200)
        self.send_header("Content-type", "application/json")
        self.end_headers()

        options = []
        for item in os.listdir(<YOUR_PATH_HERE>):
            try:
                options.append(dict(key=item, value=item))
            except psutil.NoSuchProcess:
                pass

        self.wfile.write(json.dumps(dict(options=sorted(options, key=lambda p: p['value'], reverse=True))))
```
