### ISSUE TITLE
Can it be made to reload based on changes to dependant parameters?

### ISSUE THREAD

**Issue by tombburnell** [grundic/teamcity-web-parameters#19]
I'd like to be able to have arguments populated based on the value of other choices:

arg1 with values populate from url  http://rest/arg1
arg2 with values populate from url http://rest/arg2?arg1=%arg1%

I'd like arg2 to be dynamically populated based on value of arg1.
Currently, selected an option for arg1 does not cause arg2 options to be reloaded.

**Comment by tombburnell** [comment]
I've since realised issue 1 was requesting the same thing.

I suggest voting for this issue that I created.. https://youtrack.jetbrains.com/issue/TW-50619

**Comment by grundic** [comment]
Yep, #16 is asking for the same. Thank you for created issue, will vote for it.

I will close this as duplicate then.
