### ISSUE TITLE
Error connecting to Web-service makes field unusable

### ISSUE THREAD

**Issue by westshawn** [grundic/teamcity-web-parameters#3]
Configure a web-parameters field with an inaccessible url (to simulate the web-service not responding).

Click "Run..."
The select list is replaced by a red box with the text 
```
Failed to execute request
```
This makes the build unusable.

Is it possible to catch any error and make the field a text input instead?
Maybe the error could be displayed in hint text, or just below the text box?

**Comment by grundic** [comment]
@westshawn ,
there is an option "Enable edit on error". Could you check, whether is solves your problem?

**Comment by westshawn** [comment]
That's exactly what I was looking for.

Thanks for the quick "fix" :-)

**Comment by grundic** [comment]
No problem! ;)
Please, let me know if there is any functionality missing or you have encounter an issue.
Keep in touch!
