### ISSUE TITLE
Option to always allow text override of webselect results.

### ISSUE THREAD

**Issue by westshawn** [grundic/teamcity-web-parameters#32]
We sometimes have a case where the webselect call is successful, but the source data is missing a value that we want to use. 

Currently there is an option to allow text override if the webselect call returns an error.

Please consider an adding a config option to allow the user to type and have it override the list values even when the web call is successful. 

Maybe keep the current filtering functionality where the input value matches against values in the list, but then if the value typed by the user doesn't match any of the items in the generated list, then it overrides as the value used for the parameter?

**Comment by kpron** [comment]
"tag support (user can add his own value)" look like your request?
https://raw.githubusercontent.com/grundic/teamcity-web-parameters/master/demo/configuration.png

**Comment by westshawn** [comment]
Yes @kpron , tag support works for this.
Thank you!
