### ISSUE TITLE
Unable to get plugin to work on TeamCity free version

### ISSUE THREAD

**Issue by DVGeoffrey** [grundic/teamcity-web-parameters#4]
Hello,
I've just downloaded TeamCity for Mac OSX and am unable to get your plugin to work.  I've got the plugin installed (TC lists it as one of the installed plugins) but the "Web populated select" option in the Spec window is not showing up.  Let me know if you need any more information.

**Comment by grundic** [comment]
Hello, @DVGeoffrey!
I've just downloaded latest 9.1.1 version of TeamCity and tested it on my mac - everything works like a charm.
You have to click on `Edit` button next to `Spec` label. In the appeared window there should be `Type` select box, in which you should be able to select `Web populated select`.

Unfortunately, right now I'm going to vacation without my notebook. In case of any question you can ask me here and I'll try to answer them, but it could come with some delay.
Also if it's really bug, the expected date of it to be fixed also could be postponed by two weeks.

**Comment by DVGeoffrey** [comment]
I've definitely done these steps and have had no luck.  However, I've moved on to installing your plugin on our development TC and am seeing it work!  I'm going to close this and chalk it up to me probably misconfiguring something.  Thanks for being quick to respond and enjoy your vacation.
