### ISSUE TITLE
Support for multiple?

### ISSUE THREAD

**Issue by toddgerman1** [grundic/teamcity-web-parameters#6]
Teamcity supports 'Allow multiple selection' when using a built-in Select list. Can you please support this feature in your Web Populated Select?

Thank you,
Todd

**Comment by grundic** [comment]
Hi Todd,
Sorry for veeeerryy loooonngg reply... I was busy.
Yep, sure, I think it's a good idea. Will try to implement it in the near future.
Thank you!

**Comment by grundic** [comment]
I fixed that in [v.1.5.0](https://github.com/grundic/teamcity-web-parameters/releases/tag/v1.5.0).
