### ISSUE TITLE
Compatibility with scheduled trigger?

### ISSUE THREAD

**Issue by westshawn** [grundic/teamcity-web-parameters#8]
Hi @grundic,

The plugin is fantastic on manual runs!

When I run via scheduled trigger, the web select fields have blank values.

Is it possible to adjust the plugin to support auto-triggered builds?
Or, would that be something JetBrains would need to change in TeamCity?

**Comment by grundic** [comment]
Hello, @westshawn,
Thanks for your response.
Could you please specify, how would you set value to the select box? Should it be hardcoded or you wish to configure it depending on some parameter? 
For the first case you can set default value in build parameters.
For the second case I have #5, which I can't resolve yet [here](https://devnet.jetbrains.com/thread/473231?tstart=0) is question on JetBrains forum regarding it).

If you still have questions, please feel free to ask me.

**Comment by westshawn** [comment]
I would like it to use the first value in the list by default.

My use case is to run the build with the latest version returned by each of several select lists.

**Comment by grundic** [comment]
@westshawn, 
Ok, I got it.
I think it's possible to implement, but I'm in process of moving to another city and accommodating, so not much time left for home projects :) 
I'll try my best, but without any promising.

**Comment by westshawn** [comment]
@grundic,
Can you describe the area of the code, or type of change you think will allow the build to use the first query item by default?
Maybe I can try implementing it.

Thanks for your work on this, and best of luck with your move!

**Comment by grundic** [comment]
@westshawn,
I'm not sure, but I would start with web/parameters/controller/WebParameterController.java file, add some breakpoints to the methods and investigate the pipeline of the run process.

**Comment by westshawn** [comment]
Hi @grundic,
I hope your move went well. 

Do you have any plans in the near future to investigate compatibility with scheduled trigger?

**Comment by grundic** [comment]
Hello @westshawn,
Yep, we successfully moved.

I have not much time, but I'll try to implement this feature.

**Comment by westshawn** [comment]
Hi @grundic,
Given your other priorities, do you estimate you'll get to it in a matter of days, weeks or months?

**Comment by grundic** [comment]
I would say weeks.
The issue doesn't look very difficult to implement, but I don't have working environment, so it could take some time to configure everything.

**Comment by grundic** [comment]
Hi, I've released a new version of the plugin, so now it should be possible to set `default` option for using in scheduled trigger:
```
        {
            "key": "Fifth item",
            "value": "500",
            "enabled": true,
            "default": true
        }
```

**Comment by westshawn** [comment]
Molodetz @grundic !
Bolshoe spasibo!

The default values work well with scheduled trigger as well as with the regular "Run" button.

One note that you might consider adding to the documentation is that v1.3 requires TeamCity server to have Java 1.8. Web-parameters v1.2 is compatible with Java 1.7, but v1.3 is not.

I noticed on scheduled builds that used a default value, the value is not displayed on the build run parameters page. The value displayed is blank.

For build runs that used a default web-parameter value, is it possible to display the actual parameter value used by the build on the build parameters page?

Bolshoe spasibo again, this is a great plugin!

**Comment by grundic** [comment]
Пожалуйста! :)
The value is not displayed on parameters page, because it's default value is empty. But you should see actual value of this parameter somewhere below, which should display real value which was used.

**Comment by westshawn** [comment]
Okay, that makes sense.
Here is the related issue: https://youtrack.jetbrains.com/issue/TW-20897

**Comment by westshawn** [comment]
@grundic,
The functionality for scheduled builds to use the default (first in the list) value works as expected.

A problem we found is that it now uses the default (first in the list) value to override a user selected value as well.

For example:
click "..."
web_select_param
```
A
B
C
```
select "B"
click "Run Build"
Click parameters tab on the build run
User Defined Parameters section:
* web_select_param = **B**

Actual Parameters on Agent section:
* web_select_param = A

**Comment by grundic** [comment]
@westshawn, that's strange.. I'll take a look at it soon.

**Comment by grundic** [comment]
@westshawn, hey!
Sorry for long absence... Personal life, work - you know :)
Here you can try release where the issue should be fixed: https://github.com/grundic/teamcity-web-parameters/releases/tag/v1.4.0
As always comments and improvements are welcome!

**Comment by westshawn** [comment]
Molodetz @grundic !
v1.4 works as expected for scheduled and manual trigger.

Bolshoe spasibo!
